name: Elm Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Setup Elm environment
        uses: JorelAli/setup-elm@v1
        with:
          elm-version: 0.19.1
      - name: install deps
        run: npm ci
      - name: run tests
        run: npm test
